In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([ [np.nan, 2, np.nan, 0], 
                    [3, 4, np.nan, 1], 
                    [np.nan, np.nan, np.nan, 5], 
                    [np.nan, 3, np.nan, 4],
                    [np.nan, np.nan, np.nan, np.nan] ],
                    columns=list('ABCD'))
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [3]:
df.isnull().sum()                  #fill gap data

A    4
B    2
C    5
D    1
dtype: int64

In [4]:
df.isna()

A      B     C      D
0   True  False  True  False
1  False  False  True  False
2   True   True  True  False
3   True  False  True  False
4   True   True  True   True

In [6]:
pd.isna(df["A"])

0     True
1    False
2     True
3     True
4     True
Name: A, dtype: bool

In [7]:
df.notna()

A      B      C      D
0  False   True  False   True
1   True   True  False   True
2  False  False  False   True
3  False   True  False   True
4  False  False  False  False

In [8]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [9]:
df.fillna(0)

A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  5.0
3  0.0  3.0  0.0  4.0
4  0.0  0.0  0.0  0.0

In [10]:
df.fillna(df.mean())

A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  5.0
3  3.0  3.0 NaN  4.0
4  3.0  3.0 NaN  2.5

In [11]:
df.fillna(df.mean()['A':'B'])

A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  5.0
3  3.0  3.0 NaN  4.0
4  3.0  3.0 NaN  NaN

In [12]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [13]:
df.fillna(method='ffill')  # ffill method

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  5.0
3  3.0  3.0 NaN  4.0
4  3.0  3.0 NaN  4.0

In [14]:
df.fillna(value={'A': 0, 'B': 1, 'C': 2, 'D': 3}, limit=1)

A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  NaN  1.0
2  NaN  1.0  NaN  5.0
3  NaN  3.0  NaN  4.0
4  NaN  NaN  NaN  3.0

In [15]:
df.fillna(value={'A': 0, 'B': 1, 'C': 2, 'D': 3})

A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  2.0  1.0
2  0.0  1.0  2.0  5.0
3  0.0  3.0  2.0  4.0
4  0.0  1.0  2.0  3.0

In [16]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [18]:
df.dropna() #remove gap data

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [19]:
df.dropna(axis=0)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [20]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [21]:
df['A'].dropna()

1    3.0
Name: A, dtype: float64

In [22]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [23]:
df.dropna(thresh=2)  #drop rows that have not at least 2 non-NaN values

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [24]:
df.dropna(how='all')  #only drop rows where all columns are NaN

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0

In [25]:
df.dropna(subset=['B'])  # only drop rows where NaN appear in specific columns B

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [26]:
#Imputing missing values

In [79]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [80]:
from sklearn.preprocessing import Imputer
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)
imr = imr.fit(df)
imputed_data = imr.transform(df.values) 

ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' (C:\Users\asus\anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [81]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  3.0 NaN  4.0
4  NaN  NaN NaN  NaN

In [82]:
imputed_data

NameError: name 'imputed_data' is not defined

In [83]:
#-------------------------nomalize data---------------------------------

In [84]:
from sklearn.preprocessing import MinMaxScaler

In [85]:
data = [[1, 50], [2, 30],[3,40]]

In [86]:
scaler = MinMaxScaler()

In [90]:
scaler.fit(data);

In [91]:
scaler.data_min_

array([ 1., 30.])

In [92]:
scaler.data_max_

array([ 3., 50.])

In [93]:
scaler.transform(data)   # (x-min) / (max-min)

array([[0. , 1. ],
       [0.5, 0. ],
       [1. , 0.5]])

In [94]:
#normalize

In [95]:
from sklearn.preprocessing import normalize

In [96]:
data

[[1, 50], [2, 30], [3, 40]]

In [97]:
n1=normalize(data,norm='l1',axis=0)
n1

array([[0.16666667, 0.41666667],
       [0.33333333, 0.25      ],
       [0.5       , 0.33333333]])

In [98]:
n2=normalize(data,norm='l2',axis=0)
n2

array([[0.26726124, 0.70710678],
       [0.53452248, 0.42426407],
       [0.80178373, 0.56568542]])

In [99]:
#example

In [100]:
import pandas as pd

In [20]:
data = {'age':[18,35,37,42,55,70],
        'salary':[1000000,2000000,2500000,3000000,4000000,7000000]}

In [102]:
df=pd.DataFrame(data)
df

age   salary
0   18  1000000
1   35  2000000
2   37  2500000
3   42  3000000
4   55  4000000
5   70  7000000

In [106]:
scaler = MinMaxScaler()

In [107]:
%%capture
scaler.fit(df);

In [108]:
scaler.data_min_

array([1.8e+01, 1.0e+06])

In [ ]:
scaler.data_max_

In [109]:
n1=normalize(df,norm='l1',axis=0)
n1

array([[0.07003891, 0.05128205],
       [0.13618677, 0.1025641 ],
       [0.14396887, 0.12820513],
       [0.16342412, 0.15384615],
       [0.21400778, 0.20512821],
       [0.27237354, 0.35897436]])

In [110]:
n2=normalize(df,norm='l2',axis=0)
n2

array([[0.16031222, 0.10830607],
       [0.31171821, 0.21661214],
       [0.32953067, 0.27076518],
       [0.37406185, 0.32491822],
       [0.48984289, 0.43322429],
       [0.62343641, 0.75814251]])

In [111]:
scaler.transform(df)   # (x-min) / (max-min)

array([[0.        , 0.        ],
       [0.32692308, 0.16666667],
       [0.36538462, 0.25      ],
       [0.46153846, 0.33333333],
       [0.71153846, 0.5       ],
       [1.        , 1.        ]])

In [ ]:
#------------------------------------------------------------

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv("C:/Users/asus/Desktop/coding/ipynb/train_Titanic.csv")

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Name         891 non-null    object 
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [27]:
df.shape  

(891, 12)

In [28]:
df.head(3)


PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   

   Survived  
0         0  
1         1  
2         1

In [29]:
def f(name):
    if '-' in name :
        return name.split(',')[1].split('.').strip()
    else:
        return 'unknown '

In [36]:
def g(tt):
    if tt in ['Mr']:
        return 1
    elif tt in ['Master']:
        return 3
    elif tt in ['Ms', 'Mlle', 'Miss']:
        return 4
    elif tt in ['Mrs','Mme']:
        return 5
    else:
        return 2

In [37]:
df['title'] = df[ 'Name'].apply(f).apply(g)
df.head(5)

AttributeError: 'list' object has no attribute 'strip'

In [38]:
t = pd.crosstab(df['title'], df['Survived'])
t

KeyError: 'title'

In [39]:
t_pct = t.div(t.sum(1).astype(float), axis=0)
t_pct

NameError: name 't' is not defined

In [40]:
t_pct.plot(kind='bar',stacked=True, title='Survival Rate by title')

plt.xlabel('title')

plt.ylabel('Survival Rate')

NameError: name 't_pct' is not defined

In [42]:
# drop unnecessary columns

In [43]:
df = df.drop(['PassengerId','Name','Ticket'], axis=1)   
df.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked  Survived
0       3    male  22.0      1      0   7.2500   NaN        S         0
1       1  female  38.0      1      0  71.2833   C85        C         1
2       3  female  26.0      0      0   7.9250   NaN        S         1
3       1  female  35.0      1      0  53.1000  C123        S         1
4       3    male  35.0      0      0   8.0500   NaN        S         0

In [44]:
# Embarked
# get_dummies: Convert categorical variable into dummy/indicator variables
edt  = pd.get_dummies(df['Embarked'])
edt

C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]

In [45]:
#edt
edt.drop(['S'], axis=1, inplace=True)

In [46]:
df = df.join(edt)
df

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked  Survived  C  \
0         3    male  22.0      1      0   7.2500   NaN        S         0  0   
1         1  female  38.0      1      0  71.2833   C85        C         1  1   
2         3  female  26.0      0      0   7.9250   NaN        S         1  0   
3         1  female  35.0      1      0  53.1000  C123        S         1  0   
4         3    male  35.0      0      0   8.0500   NaN        S         0  0   
..      ...     ...   ...    ...    ...      ...   ...      ...       ... ..   
886       2    male  27.0      0      0  13.0000   NaN        S         0  0   
887       1  female  19.0      0      0  30.0000   B42        S         1  0   
888       3  female   NaN      1      2  23.4500   NaN        S         0  0   
889       1    male  26.0      0      0  30.0000  C148        C         1  1   
890       3    male  32.0      0      0   7.7500   NaN        Q         0  0   

     Q  
0    0  
1    0  
2    0  
3    0  
4    0  
..  ..  
886  0  
887  0  
888  0  
889  0  
890  1  

[891 rows x 11 columns]

In [47]:
df.drop(['Embarked'], axis=1,inplace=True)
df.head(3)

Pclass     Sex   Age  SibSp  Parch     Fare Cabin  Survived  C  Q
0       3    male  22.0      1      0   7.2500   NaN         0  0  0
1       1  female  38.0      1      0  71.2833   C85         1  1  0
2       3  female  26.0      0      0   7.9250   NaN         1  0  0

In [48]:
df = pd.DataFrame({'Bird' : ['A', 'A', 'B', 'B', 'B'],'Speed' : [380, 370, 24, 26,np.nan]})
df

Bird  Speed
0    A  380.0
1    A  370.0
2    B   24.0
3    B   26.0
4    B    NaN

In [49]:
df.groupby(['Bird']).mean()

Speed
Bird       
A     375.0
B      25.0

In [53]:
df['Speed'] = df.groupby(['Bird'])['Speed'].transform(lambda x: x.fillna(x.mean()))
df

Bird  Speed
0    A  380.0
1    A  370.0
2    B   24.0
3    B   26.0
4    B   25.0

In [54]:
df['Age'] = df.groupby(['Pclass'])['Age'].transform(lambda x: x.fillna(x.mean()))

KeyError: 'Pclass'

In [55]:
# Cabin
# It has a lot of NaN values, so it won't cause a remarkable impact on prediction
df.drop("Cabin",axis=1,inplace=True)

KeyError: "['Cabin'] not found in axis"

In [56]:
##sexes
s = sorted(df['Sex'].unique())
s     

KeyError: 'Sex'

In [57]:
df['Sex'] = df['Sex'].map(gm).astype(int)
df['Sex'].head(5)

KeyError: 'Sex'

In [58]:
gm = dict(zip(s, range(0, len(s) + 1)))
gm

NameError: name 's' is not defined